# -*- ruby -*-

require "rubygems"
require "hoe"

# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rubyforge

Hoe.spec "discocli" do
  developer("Joaquin Lopez", "mrgus@disco-zombie.net")

  self.rubyforge_name = "secretions" # if different than "discocli"

  license "RAM" # this should match the license in the README
end

# vim: syntax=ruby
